/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-03-25 09:35:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer_002dpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Customer;

public final class change_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Customer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thay đổi thông tin</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");

	String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ request.getContextPath();
	
	String err = request.getAttribute("err") + "";
	err = (err.equals("null")) ? "" : err;
	
	Customer customer = (Customer) session.getAttribute("customer");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	if (customer == null) {
	
      out.write("\r\n");
      out.write("	<h3>\r\n");
      out.write("		Bạn cần <a href=\"");
      out.print(url);
      out.write("/customer-page/login.jsp\">đăng nhập</a> để\r\n");
      out.write("		thực hiện chức năng này, quay về <a href=\"");
      out.print(url);
      out.write("/index.jsp\">trang\r\n");
      out.write("			chủ</a>\r\n");
      out.write("	</h3>\r\n");
      out.write("	");

	} else {
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("		<div class=\"text-center mt-4\">\r\n");
      out.write("			<h2>THAY ĐỔI THÔNG TIN CÁ NHÂN</h2>\r\n");
      out.write("			<span class=\"rq\">");
      out.print(err);
      out.write("</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form class=\"regisForm\" action=\"");
      out.print(url);
      out.write("/customer-controller\"\r\n");
      out.write("			method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"activity\" value=\"changeInfo\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<h3>Thông tin khách hàng</h3>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"fullName\" class=\"form-label\">Họ và tên:</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\"\r\n");
      out.write("						value=\"");
      out.print(customer.getCustomerName());
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"gender\" class=\"form-label\">Giới tính:</label> <select\r\n");
      out.write("						class=\"\" id=\"gender\" name=\"gender\">\r\n");
      out.write("						<option></option>\r\n");
      out.write("						<option value=\"male\"\r\n");
      out.write("							");
      out.print((customer.getGender().equals("male")) ? "selected" : "");
      out.write(">Nam</option>\r\n");
      out.write("						<option value=\"female\"\r\n");
      out.write("							");
      out.print((customer.getGender().equals("female")) ? "selected" : "");
      out.write(">Nữ</option>\r\n");
      out.write("						<option value=\"other\"\r\n");
      out.write("							");
      out.print((customer.getGender().equals("other")) ? "selected" : "");
      out.write(">Khác</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"dob\" class=\"form-label\">Ngày sinh:</label> <input\r\n");
      out.write("						type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\"\r\n");
      out.write("						value=\"");
      out.print(customer.getDob().toString());
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr />\r\n");
      out.write("			<h3>Địa chỉ khách hàng</h3>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"address\" class=\"form-label\">Địa chỉ khách hàng</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"address\" name=\"address\"\r\n");
      out.write("					value=\"");
      out.print(customer.getAddress());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"receiAddress\" class=\"form-label\">Địa chỉ nhận\r\n");
      out.write("					hàng</label> <input type=\"text\" class=\"form-control\" id=\"receiAddress\"\r\n");
      out.write("					name=\"receiAddress\" value=\"");
      out.print(customer.getreceiAddress());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"buyAddress\" class=\"form-label\">Địa chỉ mua hàng</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"buyAddress\"\r\n");
      out.write("					name=\"buyAddress\" value=\"");
      out.print(customer.getbuyAddress());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"phoneNumber\" class=\"form-label\">Số điện thoại:</label> <input\r\n");
      out.write("					type=\"tel\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\"\r\n");
      out.write("					value=\"");
      out.print(customer.getPhoneNumber());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"email\" class=\"form-label\">Email:</label> <input\r\n");
      out.write("					type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("					value=\"");
      out.print(customer.getEmail());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-primary form-control mb-4\"\r\n");
      out.write("				id=\"submit\" name=\"submit\">Xác nhận thay đổi</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

	}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
