/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-03-25 08:24:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer_002dpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Customer;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Customer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Đăng ký</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".rq {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		String err = request.getAttribute("errMsg")+"";
		err = (err.equals("null"))?"":err;
		Object obj = request.getAttribute("customer");
		Customer customer = new Customer("null", "null", "null", "null", "null", 
				"null", "null", "null", null, 
				"null", "null", 0);
		if(obj!=null) {
			customer = (Customer)obj;
		}
		String customerName = (customer.getCustomerName().equals("null"))?"":customer.getCustomerName();
		String userName = (customer.getUsername().equals("null"))?"":customer.getUsername();
		String gender = (customer.getGender().equals("null"))?"":customer.getGender();
		String address = (customer.getAddress().equals("null"))?"":customer.getAddress();
		String receiAddress = (customer.getreceiAddress().equals("null"))?"":customer.getreceiAddress();
		String buyAddress = (customer.getbuyAddress().equals("null"))?"":customer.getbuyAddress();
		String dob = ((customer.getDob()+"").equals("null"))?"":(customer.getDob()+"");
		String phoneNumber = (customer.getPhoneNumber().equals("null"))?"":customer.getPhoneNumber();
		String email = (customer.getEmail().equals("null"))?"":customer.getEmail();
		String isRecei_email =  ((customer.isRecei_email()==0))?"":"checked";
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("		<div class=\"text-center mt-4\">\r\n");
      out.write("			<h2>ĐĂNG KÝ TÀI KHOẢN</h2>\r\n");
      out.write("			<span class=\"rq\">");
      out.print( err );
      out.write("</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
				+ request.getContextPath();
		
      out.write("\r\n");
      out.write("		<form class=\"regisForm\" action=\"");
      out.print(url );
      out.write("/customer-controller\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"activity\" value=\"register\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<h3>Thông tin tài khoản</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"userName\" class=\"form-label\">Tên đăng nhập:<span\r\n");
      out.write("							class=\"rq\">*</span></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"userName\" name=\"userName\" value=\"");
      out.print(userName);
      out.write("\" required=\"required\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"password\" class=\"form-label\">Mật khẩu:<span\r\n");
      out.write("							class=\"rq\">*</span></label> <input type=\"password\" class=\"form-control\"\r\n");
      out.write("							id=\"password\" name=\"password\" required=\"required\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"rePassword\" class=\"form-label\">Nhập lại mật\r\n");
      out.write("							khẩu:<span class=\"rq\">* </span> <span id=\"rePassErrorMsg\" class=\"rq\"></span>\r\n");
      out.write("						</label> <input type=\"password\" class=\"form-control\" id=\"rePassword\"\r\n");
      out.write("							name=\"rePassword\" required=\"required\" oninput=\"checkRePass()\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<h3>Thông tin khách hàng</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"fullName\" class=\"form-label\">Họ và tên:</label> <input\r\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\" value=\"");
      out.print(customerName);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"gender\" class=\"form-label\">Giới tính:</label> <select\r\n");
      out.write("							class=\"\" id=\"gender\" name=\"gender\">\r\n");
      out.write("							<option></option>\r\n");
      out.write("							<option value=\"male\" ");
      out.print((gender.equals("male"))?"selected":"");
      out.write(">Nam</option>\r\n");
      out.write("							<option value=\"female\" ");
      out.print((gender.equals("female"))?"selected":"");
      out.write(">Nữ</option>\r\n");
      out.write("							<option value=\"other\" ");
      out.print((gender.equals("other"))?"selected":"");
      out.write(">Khác</option>\r\n");
      out.write("						</select> \r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dob\" class=\"form-label\">Ngày sinh:</label> <input\r\n");
      out.write("							type=\"date\" class=\"form-control\" id=\"dob\" name=\"dob\" value=\"");
      out.print(dob);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr />\r\n");
      out.write("			<h3>Địa chỉ khách hàng</h3>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"address\" class=\"form-label\">Địa chỉ khách hàng</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"");
      out.print(address);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"receiAddress\" class=\"form-label\">Địa chỉ nhận\r\n");
      out.write("					hàng</label> <input type=\"text\" class=\"form-control\" id=\"receiAddress\"\r\n");
      out.write("					name=\"receiAddress\" value=\"");
      out.print(receiAddress);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"buyAddress\" class=\"form-label\">Địa chỉ mua hàng</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"buyAddress\"\r\n");
      out.write("					name=\"buyAddress\" value=\"");
      out.print(buyAddress);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"phoneNumber\" class=\"form-label\">Số điện thoại:</label> <input\r\n");
      out.write("					type=\"tel\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" value=\"");
      out.print(phoneNumber);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"email\" class=\"form-label\">Email:</label> <input\r\n");
      out.write("					type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print(email);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3 text-center\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"isAcept\" class=\"form-check-input\" oninput=\"checkSubmit()\"\r\n");
      out.write("					name=\"isAcept\" value=\"isAcept\" > <label for=\"isAcept\" class=\"form-label\">Bạn\r\n");
      out.write("					đồng ý với <a\r\n");
      out.write("					href=\"https://getbootstrap.com/docs/5.3/forms/overview/#overview\">điều\r\n");
      out.write("						khoản của công ty.</a> <span class=\"rq\">*</span>\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3 text-center\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"isRecei_email\" class=\"form-check-input\"\r\n");
      out.write("					name=\"isRecei_email\" ");
      out.print( isRecei_email );
      out.write("> <label for=\"isRecei_email\"\r\n");
      out.write("					class=\"form-label\">Bạn đồng ý nhận thông tin khuyến mãi qua\r\n");
      out.write("					địa chỉ email.</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-primary form-control mb-4\" id=\"submit\" name=\"submit\" disabled=\"disabled\">Đăng ký</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function checkRePass() {\r\n");
      out.write("		let password = document.getElementById(\"password\").value;\r\n");
      out.write("		let rePassword = document.getElementById(\"rePassword\").value;\r\n");
      out.write("		let errorMsg = document.getElementById(\"rePassErrorMsg\");\r\n");
      out.write("		if (rePassword!=password) {\r\n");
      out.write("			errorMsg.innerHTML = \"Mật khẩu nhập lại chưa trùng khớp!\";\r\n");
      out.write("			return true;\r\n");
      out.write("		} else {\r\n");
      out.write("			errorMsg.innerHTML =\"\";\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	function checkSubmit() {\r\n");
      out.write("		let isAcept = document.getElementById(\"isAcept\");\r\n");
      out.write("		let submit = document.getElementById(\"submit\");\r\n");
      out.write("		if (isAcept.checked == 1) {\r\n");
      out.write("			submit.removeAttribute('disabled');\r\n");
      out.write("		} else {\r\n");
      out.write("			submit.setAttribute('disabled', 'disabled')\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
